name: Godot Web

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Godot
        uses: lihop/setup-godot@c20123b19b7804a9bead6412b863450c2848f1d6
        with:
          godot-version: 4.6.2

      - name: Create build folder
        run: mkdir build\web

      - name: Export Web
        run: |
          godot --path .\project.godot --editor --headless --quit
          godot --headless --path .\project.godot --export-release "Web" --verbose .\exports\web\
          dir .\build\web

      - name: Fix structure
        run: |
          mkdir public
          move build\web\* public\
          dir .\build\web

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: public

  deploy:
    needs: build
    runs-on: windows-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
